server:
  port: 8080
spring:
  application:
    name: 19-jrtp701-user-management-api-proj-03
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root@changed
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/jrtp701_user_db
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        '[format_sql]': true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: never
  mail:
      host: smtp.gmail.com
      port: 587
      username: gs@gmail.com
      password: root@changed
      properties:
         mail:
            smtp:
               auth: true
               starttls:
                  enable: true
                  required: true
               connectiontimeout: 50000
               timeout: 5000
               writetimeout: 10000
user:
   module:
      messages:
         register-success: User is registered with Id value
         register-failure: Problem in user registration
         save-success: User saved
         save-failure: Used could not be saved
         update-success: User updated
         update-failure: User not found and not updated
         delete-success: User deleted successfully
         delete-failure: User could not be deleted
         login-success: Welcome! Login successful
         login-failure: Login unsuccessful. User account is not active
         invalid-credentials : Login unsuccessful. Your credentials are invalid. 
         find-user-by-id-success: Found user by id of value
         find-user-by-id-failure: Problem finding user by id of value
         password-not-match: New password and confirm password does not match
         password-recovered: Password successfully recovered. Check your email
         password-not-recovered: Password recovery unsuccessful. User not found, invalid credentials.
         activate-account-url: http://localhost:8080/usermanagement/api/activateUser
         account-active-status: Your user account is
         status-change-success: Status changed success
         status-change-failure: Status changed failure
      mail:
         from-email: gopesh.sharma@gmail.com
   
     
             